const fakeAddresses = [
  "Adler Salvius Gata",
  "Åkareplatsen",
  "Ålandsgatan",
  "Alfhemsgatan",
  "Älghagsgatan",
  "Almqvists Bro",
  "Alströmergatan",
  "Ånäsvägen",
  "Andra Långgatan",
  "Apelgången",
  "Arkivgatan",
  "Arsenalsgatan",
  "Artilleristen Gladers Trappor",
  "Åsgatan",
  "Aschebergsgatan",
  "August Kobbsgatan",
  "Åvägen",
  "Bäckegatan",
  "Baldersgatan",
  "Bältgatan",
  "Bangatan",
  "Barnhusgatan",
  "Barrskogsgatan",
  "Basargatan",
  "Bauersgatan",
  "Bellmansgatan",
  "Bergavägen",
  "Berzeliigatan",
  "Betaniagatan",
  "Bielkegatan",
  "Björnbärsgatan",
  "Blekeallén",
  "Blomstergatan",
  "Bockhornsgatan",
  "Bohusgatan",
  "Boråsleden",
  "Brämaregatan",
  "Brantbacken",
  "Brogatan",
  "Brunnsgatan",
  "Brunnsparken",
  "Bryggaregatan",
  "Burggrevegatan",
  "Carl Grimbergsgatan",
  "Carlandersplatsen",
  "Dämmebron",
  "Danska Vägen",
  "De Geersgatan",
  "Delsjövägen",
  "Diagonalen",
  "Djurgårdsgatan",
  "Drakegatan",
  "Drakenbergsgatan",
  "Drottninggatan",
  "Drottningtorget",
  "E6",
  "Egnahemsvägen",
  "Ekedalsgatan",
  "Ekelundsgatan",
  "Eklandagatan",
  "Ekmansgatan",
  "Eldaregatan",
  "Elfrida Andrées Gata",
  "Emigrantvägen",
  "Engelbrektsgatan",
  "Erik Dahlbergsgatan",
  "Erik Dahlbergstrappan",
  "Fabriksgatan",
  "Fagerängsgatan",
  "Falkgatan",
  "Färgaregatan",
  "Femkampsgatan",
  "Fjällgatan",
  "Flaggatan",
  "Folkungagatan",
  "Föreningsgatan",
  "Första Långgatan",
  "Fredsbron",
  "Fredsgatan",
  "Friggagatan",
  "Fritjofsstigen",
  "Fürstenbergsgatan",
  "Gamla Allén",
  "Gårdavägen",
  "Garverigatan",
  "Geijersgatan",
  "Getebergsled",
  "Gibraltargatan",
  "Gjutjärnsgatan",
  "Götaälvbron",
  "Götabergsgatan",
  "Götaplatsen",
  "Götaverksgatan",
  "Götgatan",
  "Grönsaksgatan",
  "Grönstensvägen",
  "Gudmundsgatan",
  "Gullbergsbrogatan",
  "Haga Kyrkogata",
  "Haga Östergata",
  "Hagmarksgatan",
  "Hallandsgatan",
  "Hallegatan",
  "Hantverkaregatan",
  "Hedåsgatan",
  "Herkulesgatan",
  "Herrgårdsgatan",
  "Hisingsgatan",
  "Högåsplatsen",
  "Hogenskilds trappor",
  "Hörsalsvägen",
  "Hugo Grauers gata",
  "Humlegatan",
  "Husargatan",
  "Hvitfeldtsgatan",
  "Chalmers Tvärgata",
  "Chalmersgatan",
  "J F Carpelans Gångväg",
  "Jägaregatan",
  "Jakobsdalsgatan",
  "Järntorget",
  "Järntorgsgatan",
  "Järnvågsgatan",
  "Jättegrytsgatan",
  "Johan på Gårdas Gata",
  "Jungmansgatan",
  "Källhusgatan",
  "Kämpebron",
  "Kämpegatan",
  "Kapellgatan",
  "Käppslängareliden",
  "Karin Boyes Gata",
  "Karl Gustavsgatan",
  "Karlagatan",
  "Karlavagnsgatan",
  "Karlfeldtsgatan",
  "Kärralundsgatan",
  "Kastellgatan",
  "Kemivägen",
  "Kjellbergsgatan",
  "Klamparegatan",
  "Kobbarnas väg",
  "Kompassgatan",
  "Köpmansgatan",
  "Korsgatan",
  "Korsvägen",
  "Kristinehöjdsgatan",
  "Kristinelundsgatan",
  "Kronhjortsgatan",
  "Kronhusgatan",
  "Kruthusgatan",
  "Kungsgatan",
  "Kungsportsavenyn",
  "Kungsportsbron",
  "Kungstorget",
  "Kvarnbergsgatan",
  "Kvillegatan",
  "Kvilletorget",
  "Kyrkogatan",
  "Laboratoriegatan",
  "Lagerbringsgatan",
  "Landalagatan",
  "Landsvägsgatan",
  "Läraregatan",
  "Läroverksgatan",
  "Lasarettsgatan",
  "Levgrensvägen",
  "Lilla Badhusgatan",
  "Lilla Bergsgatan",
  "Lilla Korsgatan",
  "Lilla Kungsgatan",
  "Lilla Kyrkogatan",
  "Lilla Nygatan",
  "Lindholmspiren",
  "Linnégatan",
  "Löjtnantsgatan",
  "Lorensbergsgatan",
  "Lundbyleden",
  "Lundgatan",
  "Lundgrensgatan",
  "Luntantugatan",
  "Lyckans väg",
  "Madängsgatan",
  "Magasinsgatan",
  "Majorsgatan",
  "Malmstensgatan",
  "Margretelundsgatan",
  "Mäster Johansgatan",
  "Mellangatan",
  "Mjölnaregatan",
  "Molinsgatan",
  "Mölndalsvägen",
  "Muraregatan",
  "Myntgatan",
  "Nedre Buråsliden",
  "Nedre Fogelbergsgatan",
  "Nedre Matrosgatan",
  "Neptunusgatan",
  "Nordenskiöldsgatan",
  "Nordhemsgatan",
  "Norra Ågatan",
  "Norra Allégatan",
  "Norra Hamngatan",
  "Norra Kustbanegatan",
  "Odinsgatan",
  "Olivedalsgatan",
  "Oljekvarnsgatan",
  "Olof Rudbecksgatan",
  "Orangerigatan",
  "Örgrytevägen",
  "Örngatan",
  "Oscar Hanssons Trappor",
  "Oskarsgatan",
  "Östra Hamngatan",
  "Östra Larmgatan",
  "Östra Skansgatan",
  "Övre Djupedalsgatan",
  "Övre Majorsgatan",
  "Övre Matrosgatan",
  "Övre Olskroksgatan",
  "Övre Spannmålsgatan",
  "Pallasgatan",
  "Panoramavägen",
  "Paradisgatan",
  "Parkgatan",
  "Parmmätaregatan",
  "Påskbergsgatan",
  "Persgatan",
  "Pilgatan",
  "Planetgatan",
  "Plantagegatan",
  "Platågatan",
  "Polstjärnegatan",
  "Pontus Wiknersgatan",
  "Postgatan",
  "Prästgårdsängen",
  "Prinsgatan",
  "Pumpgatan",
  "Pusterviksbron",
  "Pusterviksgatan",
  "Pusterviksplatsen",
  "Raketgatan",
  "Rambergsvägen",
  "Rantorget",
  "Raoul Wallenbergs Gata",
  "Redbergsvägen",
  "Regnbågsgatan",
  "Repslagaregatan",
  "Residensbron",
  "Richertsgatan",
  "Risåsgatan",
  "Rönnbärsstigen",
  "Rörstrandsgatan",
  "Rosengatan",
  "Rosenhillsgatan",
  "Rosenlundsbron",
  "Rosenlundsgatan",
  "Rosenlundsplatsen",
  "Runebergsgatan",
  "Sankt Eriksgatan",
  "Sankt Sigfridsgatan",
  "Seminariegatan",
  "Signalgatan",
  "Sjömansgatan",
  "Skånegatan",
  "Skanstorget",
  "Skårs Allé",
  "Skårsgatan",
  "Skeppsbron",
  "Skogshyddegatan",
  "Skolgatan",
  "Skomakaregatan",
  "Skräddaregatan",
  "Skyttegatan",
  "Slätten",
  "Slussgatan",
  "Smålandsgatan",
  "Smedjegatan",
  "Söderlingsgatan",
  "Södra Allégatan",
  "Södra Hamngatan",
  "Södra Larmgatan",
  "Södra Vägen",
  "Sofierogatan",
  "Solbacken",
  "Solstigen",
  "Spannmålsgatan",
  "Spetsbergsgatan",
  "Stafettgatan",
  "Stampgatan",
  "Stavstigen",
  "Sten Sturegatan",
  "Stenabron",
  "Stigbergsliden",
  "Stockholmsgatan",
  "Stora Nygatan",
  "Storgatan",
  "Surbrunnsgatan",
  "Sveagatan",
  "Sveaplan",
  "Sven Hultins gata",
  "Fjällbo Parkväg",
  "Nymilsgatan",
  "Sälöfjordsgatan",
  "Exportgatan",
  "Eketrägatan",
  "Sanatoriegatan",
  "Lilla Åvägen",
  "Verkstadsgatan",
  "Önneredsvägen",
  "Silvergatan",
  "Tegelbruksgatan",
  "Telegrafgatan",
  "Televisionens väg",
  "Tegnérsgatan",
  "Templargatan",
  "Templet",
  "Terra Nova Gatan",
  "Terrassgatan",
  "Tidbloms Gata",
  "Timmermansgatan",
  "Tivoligatan",
  "Tjugotalsgatan",
  "Tjärhovsgatan",
  "Tollsgatan",
  "Torggatan",
  "Torra Gatan",
  "Torpagatan",
  "Torpavägen",
  "Torpvägen",
  "Torstensonsgatan",
  "Tosserydsgatan",
  "Trädgårdsgatan",
  "Traktorvägen",
  "Tranåsgatan",
  "Tranviksgatan",
  "Tredje Långgatan",
  "Tredje Tvärgatan",
  "Trelleborgsgatan",
  "Trivselvägen",
  "Troedssonsgatan",
  "Troedssonsliden",
  "Trollebergsgatan",
  "Trollhättansvägen",
  "Trollhättanstrappan",
  "Trollsländegatan",
  "Träffgatan",
  "Träslövsvägen",
  "Trätorget",
  "Trädgårdsföreningen",
  "Trädgårdsgatan",
  "Tunbytorpsgatan",
  "Tunnbindaregatan",
  "Tunnelgatan",
  "Tunvägen",
  "Tvärgatan",
  "Tyrgatan",
  "Tyska Bron",
  "Tyska Kyrkogatan",
  "Tyska Mässan",
  "Tyskbagaregatan",
  "Tyska Skolgatan",
  "Tyra Stålhandskes Gata",
  "Ugglegatan",
  "Ullbergsgatan",
  "Ullevigatan",
  "Ulrikagatan",
  "Ulrikedalsgatan",
  "Ulrikestigen",
  "Ulriketorpsgatan",
  "Universitetsplatsen",
  "Universitetsvägen",
  "Uppgången",
  "Uppsala Allé",
  "Uppströmsslingan",
  "Valhallagatan",
  "Vallgatan",
  "Västra Hamngatan",
  "Västra Larmgatan",
  "Västra Långgatan",
  "Västra Nordstan",
  "Västra Strandgatan",
  "Västra Torggatan",
  "Västra Vägen",
  "Västra Västers Gatan",
  "Västra Ågatan",
  "Västra Ångvägen",
  "Västra Änggårdsgatan",
  "Växthusgatan",
  "Veddigevägen",
  "Vejdesgatan",
  "Västra Älvsborgsgatan",
  "Vikingagatan",
  "Vimpelgatan",
  "Vindragaregatan",
  "Vintergatan",
  "Vårväderstorget",
  "Vårvädersgatan",
  "Västra Väggaregatan",
  "Wavrinskys Plats",
  "Wieselgrensplatsen",
  "Wieselgrensgatan",
  "Wieselgrensplatsen",
  "Wolffs Gata",
  "Wollmar Yxkullsgatan",
  "Wollmar Yxkulls Plats",
  "Ytterbyvägen",
  "Önneredsvägen",
  "Östra Vägen",
  "Östra Vintergatan",
  "Östra Ågatan",
  "Östra Änggårdsgatan",
  "Övre Husargatan",
  "Övre Husargatan",
  "Övre Husargatan",
  "Övre Husargatan",
  "Övre Husargatan"
];

const input = document.getElementById("input");

const dropdown = document.createElement("ul");
dropdown.id = "dropdownList";

Object.assign(dropdown.style, {
  position: "absolute",
  zIndex: "1000",
  background: "#fff",
  border: "1px solid #ccc",
  borderRadius: "0.375rem",
  boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  listStyle: "none",
  padding: "0.25rem 0",
  margin: "0",
  display: "none",
  maxHeight: "240px",
  overflowY: "auto",
  width: input.offsetWidth + "px",
  fontSize: window.getComputedStyle(input).fontSize,
  fontFamily: window.getComputedStyle(input).fontFamily,
  boxSizing: "border-box"
});

document.querySelector(".searchbar").appendChild(dropdown);

function filterAddresses() {
  const searchValue = input.value.toLowerCase();
  dropdown.innerHTML = "";

  if (searchValue === "") {
    dropdown.style.display = "none";
    return;
  }

  const filtered = fakeAddresses.filter(addr =>
    addr.toLowerCase().includes(searchValue)
  );

  if (filtered.length === 0) {
    dropdown.style.display = "none";
    return;
  }

  filtered.forEach(addr => {
    const li = document.createElement("li");
    li.textContent = addr;
    Object.assign(li.style, {
      padding: "8px",
      cursor: "pointer"
    });
    li.onclick = () => {
      input.value = addr;
      dropdown.innerHTML = "";
      dropdown.style.display = "none";
    };
    li.onmouseover = () => li.style.background = "#f0f0f0";
    li.onmouseout = () => li.style.background = "white";
    dropdown.appendChild(li);
  });

  dropdown.style.display = "block";
}
input.addEventListener("keydown", (event) => {
  if (event.key === "Enter") {
    event.preventDefault();
    const address = input.value.trim();
    if (address !== "") {
      window.location.href = `../frontend/galleri.html?address=${encodeURIComponent(address)}`;
    }
  }
});

input.addEventListener("input", filterAddresses);

document.addEventListener("click", (e) => {
  if (!e.target.closest(".searchbar")) {
    dropdown.style.display = "none";
  }
});
